services:
  node-app:
    build: .
    ports:
      - "${VIRTUAL_PORT}:${VIRTUAL_PORT}"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
  nginx:
    image: nginx
    depends_on:
      - node-app
    env_file:
      - .env
    expose:
      - ${VIRTUAL_PORT}

networks:
  default:
    name: nginx-proxy